# Generated by Django 3.0 on 2019-12-17 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('origin_country', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('year_of_creation', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=30)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('year_of_birth', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('label', models.ManyToManyField(to='music.Label')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('features', models.TextField(blank=True, null=True)),
                ('genre', models.CharField(choices=[('C', 'Crossbreed'), ('D', 'Drumstep'), ('J', 'Jump up'), ('L', 'Liquid'), ('N', 'Neurofunk'), ('O', 'Other')], max_length=1)),
                ('release_date', models.DateField()),
                ('duration', models.DecimalField(decimal_places=2, help_text='in Minutes', max_digits=5)),
                ('label', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.Label')),
                ('producer', models.ManyToManyField(to='music.Musician')),
            ],
        ),
    ]
