# Generated by Django 3.0 on 2019-12-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='producer',
            field=models.ManyToManyField(blank=True, related_name='songs', to='music.Musician'),
        ),
    ]
