# Generated by Django 3.0 on 2020-01-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20191218_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='label',
            field=models.ManyToManyField(related_name='producer', to='music.Label'),
        ),
    ]
